spring.application.name=Book-Store
spring.datasource.url=jdbc:mysql://localhost:3306/MYBEST
spring.datasource.username=root
spring.datasource.password=XXXX!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.enabled=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=panchamayush@gmail.com
spring.mail.password=XXXXXXXXXXXXX
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
twilio.account.sid=XXXXXXXXXXXXXXXX
twilio.auth.token=XXXXXXXXXXXXXXX
twilio.phone.number=XXXXXXXXXXXXXXXX
spring.security.oauth2.client.registration.google.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=profile,email
